apiVersion: v1
kind: Service
metadata:
  name: senolibrary
  labels:
    app: senolibrary
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
  selector:
    app: senolibrary
    tier: backend
